In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [2]:
iris=datasets.load_iris()

In [3]:
x=iris.data
y=iris.target

In [4]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [5]:
from sklearn.neural_network import MLPClassifier

In [6]:
clf=MLPClassifier( hidden_layer_sizes=(20,),max_iter=2000)

In [7]:
clf.fit(x_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(20,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=2000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [8]:
clf.score(x_test,y_test)

1.0

In [9]:
clf.coefs_

[array([[-6.61643688e-11,  1.93981694e-20, -4.55611189e-01,
         -2.56255041e-01, -6.61056737e-04, -1.91192157e-15,
         -4.81155874e-01,  2.58115319e-23,  6.99296693e-01,
         -2.18805878e-02, -1.89000570e-02,  3.91943326e-01,
         -8.27650034e-02,  2.58958152e-01, -2.76043613e-04,
         -3.43787482e-03,  3.17942041e-01, -5.39835609e-01,
         -4.35353056e-02, -4.36204725e-09],
        [ 1.44839661e-18, -3.59841572e-05,  2.64881454e-01,
         -7.73589041e-02,  1.86190372e-13, -2.14843968e-05,
         -3.29083363e-01, -6.73762559e-04,  6.47468006e-01,
         -1.22422472e-01, -1.04192496e-02,  4.82877380e-01,
         -1.95192687e-02, -4.28758616e-01, -4.17325144e-10,
         -3.58130338e-05, -2.44163327e-01,  3.13787325e-01,
         -6.53942330e-02, -5.33916317e-03],
        [-2.43489317e-05, -1.32784497e-09,  3.01448457e-01,
          1.09949432e+00,  5.03952453e-06,  8.83288505e-08,
          6.97544357e-01, -4.95236659e-03, -6.50121848e-01,
         -1.

In [10]:
len(clf.coefs_)

2

In [11]:
clf.coefs_[0].shape,clf.coefs_[1].shape

((4, 20), (20, 3))

In [12]:
clf.intercepts_[0].shape,clf.intercepts_[1].shape

((20,), (3,))

# Building our own Neural Network
# i) No hidden layer

In [1]:
import numpy as np

In [14]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,0,0,1]]).T

In [15]:
X.shape,Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [13]:
weights=2*np.random.random((2,1))-1
bais=2*np.random.random(1)-1
lr=0.1
weights,bais

(array([[0.35483051],
        [0.15197958]]),
 array([0.88724718]))

In [19]:
output0=X

In [20]:
output=sig(np.dot(output0,weights)+bais)
output

array([[0.27624435],
       [0.39642971],
       [0.31728832],
       [0.44436693]])

# ii)With Hidden Layer

In [21]:
wh=2*np.random.random((2,2))-1
bh=2*np.random.random((1,2))-1
wo=2*np.random.random((2,1))-1
bo=2*np.random.random((1,1))-1

In [22]:
output0=X
outputHidden=sig(np.dot(output0,wh)+bh)
output=sig(np.dot(outputHidden,wo)+bo)
output

array([[0.41065129],
       [0.41881415],
       [0.4102889 ],
       [0.41671332]])

# Backward Propagation

In [29]:
for iter in range(10000):
    output0=X
    output=sig(np.dot(output0,weights)+bais)
    first_term=output-Y
    input_of_the_last_layer=np.dot(output0,weights)+bais
    second_term=derivativeSig(input_of_the_last_layer)
    first_two=first_term*second_term
    first_two.shape

    changes=np.array([[0.0],[0.0]])
    for i in range(2):
        for j in range(4):
            changes[i][0]=first_two[j][0]*output0[j][i]
    weights=weights-lr*changes
    bais_changes=0.0
    for j in range(4):
        bais_changes+=first_two[j][0]*1
        bais = bais-lr*bais_changes
output=sig(np.dot(X,weights)+bais)
print(weights)
print(bais)
print(output)

[[4.33582993]
 [4.5037386 ]]
[-6.84687129]
[[0.00106165]
 [0.08761317]
 [0.07508776]
 [0.8800282 ]]


In [32]:
for iter in range(10000):
    output0=X
    output=sig(np.dot(output0,weights)+bais)
    first_term=output-Y
    input_of_the_last_layer=np.dot(output0,weights)+bais
    second_term=derivativeSig(input_of_the_last_layer)
    first_two=first_term*second_term
    first_two.shape

    changes=np.dot(output0.T,first_two)
    weights=weights-lr*changes
    bais_changes=np.sum(first_two)
    bais = bais-lr*bais_changes
output=sig(np.dot(X,weights)+bais)
print(weights)
print(bais)
print(output)

[[5.25960087]
 [5.3020944 ]]
[-8.01673817]
[[3.29785535e-04]
 [6.21147705e-02]
 [5.96848254e-02]
 [9.27233996e-01]]


# Implementing a general neural network

In [10]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,1,1,0]]).T

In [11]:
wh=2*np.random.random((2,2))-1
bh=2*np.random.random((1,2))-1
wo=2*np.random.random((2,1))-1
bo=2*np.random.random((1,1))-1

In [14]:
for iter in range(10000):
    output0=X
    inputHidden=np.dot(output0,wh)+bh
    outputHidden=sig(inputHidden)
    inputForOutputLayer=np.dot(outputHidden,wo)+bo
    output=sig(inputForOutputLayer)

    first_term_of_output_layer=output-Y
    second_term_of_output_layer=derivativeSig(inputForOutputLayer)
    first_two_terms_of_output_layer=first_term_of_output_layer*second_term_of_output_layer

    first_term_of_hidden_layer=np.dot(first_two_terms_of_output_layer,wo.T)
    second_term_of_hidden_layer=derivativeSig(inputHidden)
    first_two_terms_of_hidden_layer=first_term_of_hidden_layer*second_term_of_hidden_layer

    changes_output=np.dot(outputHidden.T,first_two_terms_of_output_layer)
    changes_output_bais=np.sum(first_two_terms_of_output_layer,keepdims=True,axis=0)

    changes_hidden=np.dot(output0.T,first_two_terms_of_hidden_layer)
    changes_hidden_bais=np.sum(first_two_terms_of_hidden_layer,keepdims=True,axis=0)

    wo=wo-lr*changes_output
    bo=bo-lr*changes_output_bais

    wh=wh-lr*changes_hidden
    bh=bh-lr*changes_hidden_bais

output0=X
inputHidden=np.dot(output0,wh)+bh
outputHidden=sig(inputHidden)
inputForOutputLayer=np.dot(outputHidden,wo)+bo
output=sig(inputForOutputLayer)
output,wo,bo,wh,bh

(array([[0.06754071],
        [0.93852165],
        [0.94469359],
        [0.06018995]]),
 array([[6.98760508],
        [6.85385928]]),
 array([[-3.4104974]]),
 array([[-4.76596175,  5.69214219],
        [ 4.42016004, -5.56288645]]),
 array([[-2.44640876, -3.36721694]]))